### ISSUE TITLE
Check zkey compatibility

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#412] opened 2022-04-18 15:41 UTC
Given zkeys could generate a invalid proof(see: https://github.com/appliedzkp/maci/issues/390). Checking if given zkeys are valid to a provisioned  `VkRegistry` contract will be useful.

**Comment by ctrlc03** [comment] 2023-10-23 10:14
is this a duplicate of this or can they be made 1 issue rather than 2? https://github.com/privacy-scaling-explorations/maci/issues/447

**Comment by ctrlc03** [comment] 2023-12-15 13:32
Seems like this can be closed, please re open if this is a mistake. We can check that the vkeys set in the VkRegistry contract are correct using `checkVerifyingKey`

**Closed by ctrlc03** 2023-12-15 13:32 UTC
Labels: devops
