### ISSUE TITLE
Batch deposits and variable-length verification keys

### ISSUE THREAD

**Issue by weijiekoh** [privacy-scaling-explorations/maci#111] opened 2020-05-28 03:51 UTC
https://hackmd.io/xdT2x2-AQqmwrluZ2jkSxg

**Comment by ctrlc03** [comment] 2024-07-15 07:41
Closing this as part is duplicate of #102 and we do have a VkRegistry to allow use of different VKs without knowing the stateTreeDepth in advance

**Closed by ctrlc03** 2024-07-15 07:41 UTC
Labels: question
